remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


title: Grupo de Estudos Avançados da ESTG-Almaga
description: Estimular o aprendizado de tópicos relacionaos a Gestão e Tecnologia.
